export default {
  id: "zenmux",
  priority: 116,
  alias: "zenmux",
  uiAlias: "zenmux",
  display: {
    name: "ZenMux",
    icon: "layers",
    color: "#6366F1",
    textIcon: "ZM",
    website: "https://zenmux.ai",
    notice: {
      apiKeyUrl: "https://zenmux.ai",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://zenmux.ai/v1/chat/completions",
    validateUrl: "https://zenmux.ai/v1/models",
  },
  serviceKinds: ["llm", "embedding", "image"],
  embeddingConfig: {
    baseUrl: "https://zenmux.ai/v1/embeddings",
    authType: "apikey",
    authHeader: "bearer",
  },
  imageConfig: {
    baseUrl: "https://zenmux.ai/v1/images/generations",
  },
  models: [
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4-8", name: "Claude Opus 4.8" },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "kimi-k3-free", name: "Kimi K3 (Free)", hasFree: true },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "step-3.7-flash-free", name: "Step 3.7 Flash Free", hasFree: true },
    { id: "qwen3.7-plus", name: "Qwen 3.7 Plus" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "minimax-m3", name: "MiniMax M3" },
  ],
  modelsFetcher: { url: "https://zenmux.ai/v1/models", type: "openai" },
  passthroughModels: true,
};
